"""add_api_key

Revision ID: 7fe0d02cfc09
Revises: 9e896b850c97
Create Date: 2025-06-29 19:13:09.229296

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7fe0d02cfc09"
down_revision: Union[str, Sequence[str], None] = "9e896b850c97"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("apps", sa.Column("api_key", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("apps", "api_key")
    # ### end Alembic commands ###
