"""create_tables_with_sqlalchemy

Revision ID: 7d3462a29ce1
Revises: f867cdfdf44a
Create Date: 2025-06-28 19:41:57.827731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d3462a29ce1'
down_revision: Union[str, Sequence[str], None] = 'f867cdfdf44a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_connection_health_active'), table_name='connection_health')
    op.drop_index(op.f('idx_uid_tracking_account_folder'), table_name='uid_tracking')
    op.drop_index(op.f('idx_webhook_logs_account_created'), table_name='webhook_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_webhook_logs_account_created'), 'webhook_logs', ['account_email', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_uid_tracking_account_folder'), 'uid_tracking', ['account_email', 'folder'], unique=False)
    op.create_index(op.f('idx_connection_health_active'), 'connection_health', ['is_active', 'last_success_at'], unique=False)
    # ### end Alembic commands ###
